name: Publish Node.js Package
on:
  push: {branches: master}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
      working-directory: ./lib/lib
    - run: npm publish
      working-directory: ./lib/lib
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MY_NPM_TOKEN }}
